Домашнє завдання №1 Варіант 13


In [3]:
 import numpy as np

1. Створіть одновимірний масив (вектор) зі зростаючою геометричною послідовністю, де кожне наступне число більше попереднього в 2 рази, починаючи з 2, та виведіть його значення.

In [16]:

elements = 10

progresia = np.zeros(elements)
progresia[0] = 2

for i in range(1, elements):
    progresia[i] = progresia[i - 1] * 2

print('Геометрична прогресія:')
print(progresia)

Геометрична прогресія:
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими значеннями натуральних чисел, починаючи з 1, та виведіть його значення.



In [32]:

arr = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        arr[i, j] = 1 / (i * 3 + j + 1)

print('Матриця arr:')
print(arr)


Матриця arr:
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]


3.Створіть масив розміром 10x10, заповніть його випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть максимальний елемент.

In [33]:
arr = np.random.uniform(-10, 10, (10, 10))


max_element = np.max(arr)


print("Масив arr:")
print(arr)
print('Максимальний елемент:')
print(max_element)

Масив arr:
[[-1.24211144  4.44267646 -8.08400567  4.3847168   6.77506611  3.06604925
   0.42800477 -5.53981553 -4.41342113 -6.26636629]
 [ 9.69758962 -7.21697109 -0.42816043  0.82523392 -0.52372492  3.16087673
  -0.58138111 -4.0246648  -7.06475609 -5.87321172]
 [-6.1919321   3.50002993 -6.11840829  6.24259217 -4.4071685   1.1123368
   6.87300659 -6.95427443 -2.60099387  3.13071018]
 [ 6.22550654 -3.03874738  7.90722482 -0.94017893 -7.16852189 -2.89729061
  -2.9726378   6.59332894  1.59029415 -1.82755538]
 [ 0.7597249   5.37138343  3.62236245  0.67364106 -3.58026709 -4.37567798
  -8.10644726  3.71619096 -7.74000059  1.81196292]
 [-0.98782083  1.8245128  -1.74004544 -8.76060192 -5.97405632  7.67028474
   5.04923455  5.99714206  4.97245352 -0.41907208]
 [-0.68515452  5.35503868 -0.9241962  -5.11626563  4.21517904  1.32116555
   1.06012571 -1.33399389 -5.9327017   6.19184483]
 [ 8.41227047 -6.23367989  9.88633751  3.16874877 -2.28748131 -7.65156207
  -0.81793745 -6.80289339 -1.90795917  1.

4.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця, менших за 0.5.

In [34]:

arr= np.random.rand(3, 3)

sum = np.sum(arr < 0.5, axis=0)

print("Масив arr")
print(arr)
print("Сума елементів")
print(sum)


Масив arr
[[0.0191577  0.94558344 0.45890738]
 [0.21759554 0.78476478 0.38720726]
 [0.97007315 0.22112231 0.45542438]]
Сума елементів
[2 1 3]


5.Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання та множення.


In [35]:

a = np.random.uniform(-2, 2, (6))


b = np.random.uniform(-2, 2, (6))

print("Масив a")
print(a)
print("Масив b")
print(b)

print("Сума масивів ")
print("a + b = ", a + b)

print("Різниця масивів ")
print("a - b = ", a - b)

print("Добуток масивів ")
print("a * b = ", a * b)

Масив a
[ 0.4490374  -0.86804719 -1.50661007  1.92721101 -0.87393886 -1.10410632]
Масив b
[ 0.12887483  0.85305054 -0.26559601 -1.71347956  0.26075497  0.84698796]
Сума масивів 
a + b =  [ 0.57791223 -0.01499665 -1.77220607  0.21373145 -0.61318389 -0.25711837]
Різниця масивів 
a - b =  [ 0.32016257 -1.72109772 -1.24101406  3.64069057 -1.13469383 -1.95109428]
Добуток масивів 
a * b =  [ 0.05786962 -0.74048812  0.40014962 -3.30223667 -0.2278839  -0.93516476]


6. Створіть два вектори розміром 8, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [39]:

a = np.random.randint(-10, 10, (8))
b = np.random.randint(-10, 10, (8))


scalar = np.dot(a, b)

print("Масив a")
print(a)
print("Масив b")
print(b)
print("Скалярний добуток: ", scalar)

Масив a
[ 6  0  6  2  3 -4  7  9]
Масив b
[ 3  0  4 -9  0  3  8  3]
Скалярний добуток:  95


7.Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.

In [40]:

a = np.random.randint(1, 8, (3, 2))


b = np.random.randint(1, 8, (2, 2))


multiply = np.dot(a, b)

print("Матриця a")
print(a)
print("Матриця b")
print(b)

print("Добуток матриць")
print(multiply)

Матриця a
[[1 6]
 [7 6]
 [6 4]]
Матриця b
[[4 1]
 [4 6]]
Добуток матриць
[[28 37]
 [52 43]
 [40 30]]


8.Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [41]:
a = np.random.randint(1, 15, (2, 2))


b = np.linalg.inv(a)


print("Матриця A:")
print(a)
print("Обернена матриця B:")
print(b)

Матриця A:
[[2 9]
 [6 8]]
Обернена матриця B:
[[-0.21052632  0.23684211]
 [ 0.15789474 -0.05263158]]


9. Створіть матрицю розміром 7x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [42]:
a = np.random.rand(7,3)
b = np.transpose(a)
print("Матриця a:")
print(a)
print("Транспонована матриця b:")
print(b)

Матриця a:
[[0.03808859 0.41443687 0.97201759]
 [0.52684344 0.08235135 0.12115871]
 [0.68866687 0.19583402 0.84976517]
 [0.7013188  0.03177652 0.81065188]
 [0.15071401 0.13720436 0.21538791]
 [0.55748575 0.38542324 0.8875739 ]
 [0.09118662 0.45418371 0.52935704]]
Транспонована матриця b:
[[0.03808859 0.52684344 0.68866687 0.7013188  0.15071401 0.55748575
  0.09118662]
 [0.41443687 0.08235135 0.19583402 0.03177652 0.13720436 0.38542324
  0.45418371]
 [0.97201759 0.12115871 0.84976517 0.81065188 0.21538791 0.8875739
  0.52935704]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими
дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [43]:
matr = np.random.randint(1, 10, size=(3, 4))
vect = np.random.randint(1, 10, size=4)


multiply = np.dot(matr, vect)

# Печатаємо матрицю A, вектор b та добуток c
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)
print("Добуток:")
print(multiply)

Матриця:
[[7 9 1 7]
 [4 8 1 4]
 [4 8 3 1]]
Вектор:
[2 8 2 7]
Добуток:
[137 102  85]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які більше за відповідний елемент вектору.

In [50]:
a = np.random.random((2, 3))


b = np.random.random(3)


greaterElements = []
for i in range(2):
    for j in range(3):
        if a[i, j] > b[i]:
            greaterElements.append(a[i, j])

sums = np.sum(greaterElements)

print("Матриця a:")
print(a)
print("Вектор b:")
print(b)
print("Сума елементів матриці, які більше за відповідний елемент вектору:")
print(sums)

Матриця a:
[[0.38455648 0.7313946  0.07925824]
 [0.58629932 0.27879977 0.95989999]]
Вектор b:
[0.60900967 0.79311708 0.11982851]
Сума елементів матриці, які більше за відповідний елемент вектору:
1.6912945909522938


12. Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів першого рядка першої матриці.

In [51]:
a = np.random.randint(1, 10, (6, 6))


b = np.random.randint(1, 10, (6, 6))


sum = np.sum(a[0, :])

# Печатаємо матриці A та B
print("Матриця a:")
print(a)
print("Матриця b:")
print(b)
print("Сума елементів першого рядка першої матриці:")
print(sum)

Матриця a:
[[5 7 9 4 1 1]
 [4 6 1 3 5 2]
 [6 6 6 6 8 7]
 [5 6 5 4 4 3]
 [8 9 9 4 3 4]
 [3 8 8 3 1 2]]
Матриця b:
[[3 3 5 1 3 5]
 [6 2 8 6 4 2]
 [1 4 6 4 9 1]
 [7 6 1 2 6 5]
 [8 5 7 2 5 7]
 [7 4 5 5 3 8]]
Сума елементів першого рядка першої матриці:
27


13.Створіть дві матриці розміром 5x5, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть добуток їх елементів.

In [52]:
a = np.random.random((5, 5))


b = np.random.random((5, 5))


product = np.prod(a * b)


print("Матриця a:")
print(a)
print("Матриця b:")
print(b)
print("Добуток елементів матриць:")
print(product)

Матриця a:
[[0.53124193 0.6115414  0.29360767 0.97762969 0.23478383]
 [0.96411002 0.14874201 0.55155274 0.43977536 0.92767833]
 [0.07547947 0.38023564 0.70189115 0.07013666 0.46001056]
 [0.76481367 0.83046031 0.54929617 0.65552019 0.90706   ]
 [0.85807669 0.83541562 0.87656678 0.40284097 0.99554559]]
Матриця b:
[[0.74363732 0.03070633 0.82414267 0.41580041 0.99064589]
 [0.54532493 0.59310104 0.47177347 0.81278431 0.72926155]
 [0.59886019 0.9647492  0.08217113 0.0651698  0.6359185 ]
 [0.78721842 0.2098491  0.50650021 0.53463698 0.27623562]
 [0.72519238 0.83291352 0.54219714 0.81597303 0.47869123]]
Добуток елементів матриць:
5.233835308007022e-17


14.Створіть матрицю розміром 6x6, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть добуток елементів матриці, які менше за їх середнє арифметичне значення.

In [53]:
a = np.random.randint(1, 100, (6, 6))


average = np.mean(a)

less = a[a < average]

product = np.prod(less)


print("Матриця a:")
print(a)
print("Середнє арифметичне значення елементів матриці:")
print(average)
print("Елементи матриці, які менше за середнє арифметичне значення:")
print(less)
print("Добуток елементів матриці, які менше за середнє арифметичне значення:")
print(product)

Матриця a:
[[87 87 51 88 88 50]
 [35 34 41 70 88  3]
 [ 6 82 74 91 68 85]
 [42  8 96 27 65 18]
 [25 16 21 82 64 68]
 [ 4 36 17 57 22 42]]
Середнє арифметичне значення елементів матриці:
51.05555555555556
Елементи матриці, які менше за середнє арифметичне значення:
[51 50 35 34 41  3  6 42  8 27 18 25 16 21  4 36 17 22 42]
Добуток елементів матриці, які менше за середнє арифметичне значення:
-2983538943175950336


15.Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найменше ціле значення в кожному рядку матриці.

In [58]:
a = np.random.random((7, 7))

min = min.reshape(-1, 1)


vect = min[:, np.newaxis]


print("Матриця a:")
print(a)
print("Вектор-стовпчик, що містить найменше ціле значення в кожному рядку матриці:")
print(vect)

Матриця a:
[[0.75272663 0.3946293  0.86687807 0.52897013 0.76401842 0.90225035
  0.59876175]
 [0.1283371  0.43239133 0.26565007 0.20778352 0.68337069 0.15325621
  0.6968216 ]
 [0.66487046 0.69378752 0.94410765 0.41441433 0.0034092  0.70247934
  0.48686626]
 [0.30588958 0.98094793 0.28155259 0.27477701 0.37429286 0.47374821
  0.21850404]
 [0.5520178  0.91430548 0.51881417 0.1668413  0.75069432 0.27151235
  0.82359277]
 [0.64581197 0.74651225 0.83656201 0.96203623 0.82467414 0.57727894
  0.89114511]
 [0.76744551 0.38440502 0.03702209 0.59283866 0.5206009  0.07649113
  0.76197471]]
Вектор-стовпчик, що містить найменше ціле значення в кожному рядку матриці:
[[[0]]

 [[0]]

 [[0]]

 [[0]]

 [[0]]

 [[0]]

 [[0]]]
